## Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
source /usr/share/autojump/autojump.zsh
setopt completealiases

ZSH_THEME="crunch"

# COMPLETION_WAITING_DOTS="true"

# Add wisely, as too many plugins slow down shell startup.
plugins=(git )

# User configuration
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games"

source $ZSH/oh-my-zsh.sh

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='mvim'
fi

# alias ohmyzsh="mate ~/.oh-my-zsh"
if [ -n "$DISPLAY" ]; then
  xset b off
fi

alias music='cmus'

nohupmplayer() {
	nohup mplayer $1 > /dev/null&
}
alias play=nohupmplayer

alias vpntcpinfra='cd ~/.vpn && sudo openvpn fw-TCP-8080-manu.ovpn'

alias ll='ls -l'

alias la='ls -al'

eval `dircolors ~/.dircolors-solarized/dircolors.256dark`

